#!/usr/bin/env python3
"""render_run_context — the missing nginx Dockerfile context for the Cloud Run publish path.

Concierge-beta **stream 7** (publish reconcile). The proven publish runbook
(`docs/WEBSITE_PUBLISH_RUNBOOK.md` §2) deploys a built `sites/<slug>/` to Cloud Run with::

    gcloud run deploy <svc> --source <ctx> --region us-central1 ...

where ``<ctx>`` is "the site + a tiny nginx Dockerfile (listen 8080, root = site,
``try_files $uri $uri/ /index.html``)". That context was **described but generated nowhere**
— so the runbook's Cloud Run leg could not actually be executed from code. This module is
that generator: given a built static site, it writes a deterministic Cloud Run deploy context
(``Dockerfile`` + ``nginx.conf`` + a copy of the site under ``site/``), ready to hand to
``gcloud run deploy --source``.

Deterministic, no network, no credentials — it only writes files. It does NOT deploy; the
gated ``gcloud run deploy`` is the caller's (Matthew-gated) step. Honesty is already enforced
at build time (the engine lint aborts on a banned claim), so this content-agnostic packager
does not re-lint — it never invents content, it only wraps the already-proven site.

NO PHI by construction — a published marketing site only. Stdlib; Python 3.8+.

Usage:
    render_run_context.py <site_dir> [--out <ctx_dir>]
    # prints the context dir path; feed it to `gcloud run deploy --source <ctx>`
"""
from __future__ import annotations

import argparse
import pathlib
import shutil
import sys
import tempfile

# nginx vhost for Cloud Run: Cloud Run routes to $PORT, default 8080. Static SPA — unknown
# paths fall back to index.html so the in-page router (app.js) owns routing. Regenerating the
# site replaces every asset, so a short cache is safe.
NGINX_CONF = """\
server {
    listen       8080;
    listen       [::]:8080;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # SPA fallback: serve the file if it exists, else hand off to the app router.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets — safe short cache (a regenerate overwrites them at the same URL).
    location ~* \\.(?:js|css|svg|png|jpe?g|gif|ico|woff2?)$ {
        expires 1h;
        add_header Cache-Control "public";
    }

    # Belt-and-suspenders headers (no PHI here regardless — public marketing only).
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options SAMEORIGIN always;

    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}
"""

# Pinned minor tag (reproducible builds); alpine = small image, fast cold starts.
DOCKERFILE = """\
# GENERATED by scripts/render_run_context.py — Cloud Run deploy context for the
# proven publish path (docs/WEBSITE_PUBLISH_RUNBOOK.md §2). Do not edit by hand;
# re-render from the built site instead. Public marketing site only — no PHI.
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY site/ /usr/share/nginx/html/
EXPOSE 8080
"""


def render_context(site_dir: pathlib.Path | str,
                   ctx_dir: pathlib.Path | str | None = None) -> pathlib.Path:
    """Write a Cloud Run deploy context for a built site. Returns the context dir.

    ``ctx_dir`` defaults to a fresh temp dir. The site is copied to ``<ctx>/site`` (never
    moved — the served ``sites/<slug>/`` is left untouched), and ``Dockerfile`` + ``nginx.conf``
    are written at the context root for ``gcloud run deploy --source <ctx>``.

    Raises ``FileNotFoundError`` if ``site_dir`` has no ``index.html`` (build the site first).
    """
    site_dir = pathlib.Path(site_dir)
    if not (site_dir / "index.html").is_file():
        raise FileNotFoundError(
            f"no index.html under {site_dir} — build the site before rendering a deploy context"
        )

    if ctx_dir is None:
        ctx_dir = pathlib.Path(tempfile.mkdtemp(prefix="shaula-run-ctx-"))
    else:
        ctx_dir = pathlib.Path(ctx_dir)
        ctx_dir.mkdir(parents=True, exist_ok=True)

    # Copy the site in fresh (idempotent: a re-render into the same ctx replaces it cleanly).
    site_out = ctx_dir / "site"
    if site_out.exists():
        shutil.rmtree(site_out)
    shutil.copytree(site_dir, site_out)

    (ctx_dir / "nginx.conf").write_text(NGINX_CONF, encoding="utf-8")
    (ctx_dir / "Dockerfile").write_text(DOCKERFILE, encoding="utf-8")
    return ctx_dir


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Render a Cloud Run deploy context (nginx Dockerfile + site) from a built site."
    )
    ap.add_argument("site_dir", help="path to a built sites/<slug>/ (must contain index.html)")
    ap.add_argument("--out", default=None, help="context dir to write (default: a fresh temp dir)")
    args = ap.parse_args(argv)

    try:
        ctx = render_context(args.site_dir, args.out)
    except FileNotFoundError as e:
        sys.stderr.write(f"{e}\n")
        return 1
    print(ctx)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
